const Patient = require('../models/Patient');
const Doctor = require('../models/Doctor');
const { sendRealWhatsAppMessage } = require('../services/whatsappService');

// Helper: Generate 6-digit random numeric string
const generateRandomPin = () => Math.floor(100000 + Math.random() * 900000).toString();

// 1. API: Register Patient at O/P Desk & Send Credentials to Real WhatsApp
exports.registerPatient = async (req, res) => {
    try {
        const { name, age, gender, phoneNumber } = req.body;

        if (!phoneNumber) {
            return res.status(400).json({ message: "WhatsApp Phone number is required!" });
        }

        // SMART ASSIGNMENT: Find General Medicine doctor on shift with the shortest queue
        const assignedDoctor = await Doctor.findOne({ 
            department: 'General Medicine', 
            isOnShift: true 
        }).sort({ currentQueueCount: 1 });

        if (!assignedDoctor) {
            return res.status(400).json({ message: "No General Doctors are currently on shift!" });
        }

        // Generate unique Patient ID and a 6-digit Password
        const patientCount = await Patient.countDocuments();
        const patientId = `PT-${1000 + patientCount + 1}`;
        const autoGeneratedPassword = generateRandomPin();

        // Create Patient in Database
        const newPatient = new Patient({
            patientId,
            name,
            age,
            gender,
            phoneNumber,
            password: autoGeneratedPassword,
            currentStatus: 'WAITING_FOR_DOCTOR',
            assignedDoctorId: assignedDoctor.doctorId
        });
        await newPatient.save();

        // Increment doctor's queue count
        assignedDoctor.currentQueueCount += 1;
        await assignedDoctor.save();

        // Format message for WhatsApp
        const whatsAppMessage = `🏥 *Chikitsya Setu (Gandhi Hospital)*\nHello *${name}*, your O/P Registration is successful!\n\n🆔 *Patient ID:* ${patientId}\n🔑 *Password:* ${autoGeneratedPassword}\n👨‍⚕️ *Doctor:* ${assignedDoctor.name} (General Medicine)\n📍 *Queue Position:* #${assignedDoctor.currentQueueCount}\n\n📲 *Login here:* http://localhost:5173`;

        // Send REAL WhatsApp Message via Twilio
        const deliveryResult = await sendRealWhatsAppMessage(phoneNumber, whatsAppMessage);

        res.status(201).json({
            message: "Patient registered successfully & credentials dispatched!",
            patient: {
                patientId: newPatient.patientId,
                name: newPatient.name,
                phoneNumber: newPatient.phoneNumber,
                currentStatus: newPatient.currentStatus
            },
            credentials: {
                patientId: newPatient.patientId,
                password: autoGeneratedPassword
            },
            assignedTo: {
                doctorId: assignedDoctor.doctorId,
                doctorName: assignedDoctor.name,
                currentQueue: assignedDoctor.currentQueueCount
            },
            whatsAppNotification: {
                recipient: phoneNumber,
                message: whatsAppMessage,
                realDelivery: deliveryResult
            }
        });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 2. API: Patient Login (with Patient ID + Password)
exports.loginPatient = async (req, res) => {
    try {
        const { patientId, password } = req.body;

        if (!patientId || !password) {
            return res.status(400).json({ message: "Please provide both Patient ID and Password." });
        }

        const patient = await Patient.findOne({ patientId: patientId.trim().toUpperCase() });
        if (!patient) {
            return res.status(404).json({ message: "Patient ID not found. Please register at O/P desk." });
        }

        if (patient.password !== password.trim()) {
            return res.status(401).json({ message: "Incorrect password. Click 'Forgot Password' to receive a WhatsApp OTP." });
        }

        // Fetch assigned doctor info
        const doctor = await Doctor.findOne({ doctorId: patient.assignedDoctorId });

        res.status(200).json({
            message: "Login successful!",
            patient: {
                patientId: patient.patientId,
                name: patient.name,
                age: patient.age,
                gender: patient.gender,
                phoneNumber: patient.phoneNumber,
                currentStatus: patient.currentStatus,
                assignedDoctor: doctor ? {
                    doctorId: doctor.doctorId,
                    name: doctor.name,
                    department: doctor.department,
                    currentQueueCount: doctor.currentQueueCount
                } : null
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 3. API: Send OTP to Real WhatsApp (Forgot Password / OTP Login)
exports.sendOtp = async (req, res) => {
    try {
        const { identifier } = req.body; // Can be patientId or phoneNumber

        if (!identifier) {
            return res.status(400).json({ message: "Please enter your Patient ID or registered Phone Number." });
        }

        const patient = await Patient.findOne({
            $or: [
                { patientId: identifier.trim().toUpperCase() },
                { phoneNumber: identifier.trim() }
            ]
        });

        if (!patient) {
            return res.status(404).json({ message: "No registered patient found with this ID or phone number." });
        }

        // Generate 6-digit OTP valid for 10 minutes
        const otp = generateRandomPin();
        patient.otp = otp;
        patient.otpExpires = new Date(Date.now() + 10 * 60 * 1000);
        await patient.save();

        const whatsAppOtpMessage = `🔐 *Chikitsya Setu Security Code*\nHello *${patient.name}*, your OTP for login is: *${otp}* (valid for 10 mins).\nUse this OTP to login directly to your portal.`;

        // Send REAL WhatsApp Message via Twilio
        const deliveryResult = await sendRealWhatsAppMessage(patient.phoneNumber, whatsAppOtpMessage);

        res.status(200).json({
            message: `OTP sent to your WhatsApp number (ending in ****${patient.phoneNumber.slice(-4)})!`,
            phoneNumber: patient.phoneNumber,
            patientId: patient.patientId,
            mockOtpForTesting: otp,
            whatsAppNotification: {
                recipient: patient.phoneNumber,
                message: whatsAppOtpMessage,
                realDelivery: deliveryResult
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 4. API: Verify OTP & Direct Login
exports.verifyOtpAndLogin = async (req, res) => {
    try {
        const { identifier, otp } = req.body;

        if (!identifier || !otp) {
            return res.status(400).json({ message: "Please enter both your ID/Phone and the OTP received." });
        }

        const patient = await Patient.findOne({
            $or: [
                { patientId: identifier.trim().toUpperCase() },
                { phoneNumber: identifier.trim() }
            ]
        });

        if (!patient) {
            return res.status(404).json({ message: "Patient not found." });
        }

        if (!patient.otp || patient.otp !== otp.trim()) {
            return res.status(400).json({ message: "Invalid OTP! Please check your WhatsApp message." });
        }

        if (patient.otpExpires && patient.otpExpires < new Date()) {
            return res.status(400).json({ message: "OTP has expired. Please request a new one." });
        }

        // Clear OTP once used
        patient.otp = undefined;
        patient.otpExpires = undefined;
        await patient.save();

        // Fetch assigned doctor info
        const doctor = await Doctor.findOne({ doctorId: patient.assignedDoctorId });

        res.status(200).json({
            message: "OTP Verified! Logged in successfully.",
            patient: {
                patientId: patient.patientId,
                name: patient.name,
                age: patient.age,
                gender: patient.gender,
                phoneNumber: patient.phoneNumber,
                currentStatus: patient.currentStatus,
                assignedDoctor: doctor ? {
                    doctorId: doctor.doctorId,
                    name: doctor.name,
                    department: doctor.department,
                    currentQueueCount: doctor.currentQueueCount
                } : null
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};
