const Patient = require('../models/Patient');
const Doctor = require('../models/Doctor');
const { sendRealFast2SMS } = require('../services/smsService');

// Helper: Generate 6-digit random numeric string
const generateRandomPin = () => Math.floor(100000 + Math.random() * 900000).toString();

// 0. API: Get all patients for list / quick selection
exports.getAllPatients = async (req, res) => {
    try {
        const patients = await Patient.find().sort({ createdAt: -1 });
        res.status(200).json(patients);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 1. API: Register Patient at O/P Desk & Send Credentials to Real Phone via Fast2SMS
exports.registerPatient = async (req, res) => {
    try {
        const { name, age, gender, phoneNumber, photoUrl } = req.body;

        if (!phoneNumber) {
            return res.status(400).json({ message: "Mobile phone number is required!" });
        }

        // SMART ASSIGNMENT: Find General Medicine doctor on shift with the shortest queue
        const assignedDoctor = await Doctor.findOne({ 
            department: 'General Medicine', 
            isOnShift: true 
        }).sort({ currentQueueCount: 1 });

        if (!assignedDoctor) {
            return res.status(400).json({ message: "No General Doctors are currently on shift!" });
        }

        // Generate unique Patient ID and a 6-digit Passcode
        const patientCount = await Patient.countDocuments();
        const patientId = `PT-${1000 + patientCount + 1}`;
        const autoGeneratedPassword = generateRandomPin();

        // Create Patient in Database
        const newPatient = new Patient({
            patientId,
            name,
            age,
            gender,
            phoneNumber,
            photoUrl: photoUrl || '',
            password: autoGeneratedPassword,
            currentStatus: 'WAITING_FOR_DOCTOR',
            assignedDoctorId: assignedDoctor.doctorId
        });
        await newPatient.save();

        // Increment doctor's queue count
        assignedDoctor.currentQueueCount += 1;
        await assignedDoctor.save();

        // Real SMS Message Body
        const smsMessage = `Chikitsya Setu: Hello ${name}! Your O/P registration is complete. Patient ID: ${patientId}, Passcode: ${autoGeneratedPassword}. Assigned: ${assignedDoctor.name} (Room 102). Track live: http://localhost:5173`;

        // Dispatch REAL SMS directly to the patient's phone!
        const smsDelivery = await sendRealFast2SMS(phoneNumber, smsMessage);

        res.status(201).json({
            message: "Patient registered successfully & Real SMS dispatched!",
            patient: {
                patientId: newPatient.patientId,
                name: newPatient.name,
                phoneNumber: newPatient.phoneNumber,
                photoUrl: newPatient.photoUrl,
                currentStatus: newPatient.currentStatus
            },
            credentials: {
                patientId: newPatient.patientId,
                password: autoGeneratedPassword
            },
            assignedTo: {
                doctorId: assignedDoctor.doctorId,
                doctorName: assignedDoctor.name,
                currentQueue: assignedDoctor.currentQueueCount
            },
            whatsAppNotification: {
                recipient: phoneNumber,
                message: `🏥 *Chikitsya Setu O/P Registration*\nHello *${name}*,\nYour digital OPD token has been generated.\n\n🆔 *Patient ID:* ${patientId}\n🔑 *Login Passcode:* ${autoGeneratedPassword}\n👨‍⚕️ *Assigned Physician:* ${assignedDoctor.name} (Room 102)\n\nTrack your live queue & reports: http://localhost:5173`
            },
            smsNotification: {
                recipient: phoneNumber,
                message: smsMessage,
                realDelivery: smsDelivery
            }
        });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 2. API: Patient Login (Patient ID + Passcode)
exports.loginPatient = async (req, res) => {
    try {
        const { patientId, password } = req.body;

        if (!patientId || !password) {
            return res.status(400).json({ message: "Please provide both Patient ID and Passcode." });
        }

        const patient = await Patient.findOne({ patientId: patientId.trim().toUpperCase() });
        if (!patient) {
            return res.status(404).json({ message: "Patient ID not found. Please register at O/P counter." });
        }

        if (patient.password.trim() !== password.trim()) {
            return res.status(401).json({ message: `Incorrect passcode for ${patient.name}. Please check your ticket/WhatsApp message.` });
        }

        const doctor = await Doctor.findOne({ doctorId: patient.assignedDoctorId });

        res.status(200).json({
            message: "Login successful!",
            patient: {
                patientId: patient.patientId,
                name: patient.name,
                age: patient.age,
                gender: patient.gender,
                phoneNumber: patient.phoneNumber,
                currentStatus: patient.currentStatus,
                assignedDoctor: doctor ? {
                    doctorId: doctor.doctorId,
                    name: doctor.name,
                    department: doctor.department,
                    currentQueueCount: doctor.currentQueueCount
                } : null
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 3. API: Send OTP to Real Phone via SMS (Forgot Passcode / OTP Login)
exports.sendOtp = async (req, res) => {
    try {
        const { identifier } = req.body;

        if (!identifier) {
            return res.status(400).json({ message: "Please enter your Patient ID or registered Mobile Number." });
        }

        const patient = await Patient.findOne({
            $or: [
                { patientId: identifier.trim().toUpperCase() },
                { phoneNumber: identifier.trim() }
            ]
        });

        if (!patient) {
            return res.status(404).json({ message: "No registered patient found with this ID or phone number." });
        }

        // Generate 6-digit OTP valid for 10 minutes
        const otp = generateRandomPin();
        patient.otp = otp;
        patient.otpExpires = new Date(Date.now() + 10 * 60 * 1000);
        await patient.save();

        const smsOtpMessage = `Chikitsya Setu: Hello ${patient.name}, your security verification OTP is ${otp}. Valid for 10 mins. Do not share.`;

        // Dispatch REAL SMS OTP!
        const smsDelivery = await sendRealFast2SMS(patient.phoneNumber, smsOtpMessage);

        res.status(200).json({
            message: `OTP dispatched via SMS to your mobile number (ending in ****${patient.phoneNumber.slice(-4)})!`,
            phoneNumber: patient.phoneNumber,
            patientId: patient.patientId,
            mockOtpForTesting: otp,
            smsNotification: {
                recipient: patient.phoneNumber,
                message: smsOtpMessage,
                realDelivery: smsDelivery
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 4. API: Verify OTP & Direct Login
exports.verifyOtpAndLogin = async (req, res) => {
    try {
        const { identifier, otp } = req.body;

        if (!identifier || !otp) {
            return res.status(400).json({ message: "Please enter both your ID/Phone and the OTP received." });
        }

        const patient = await Patient.findOne({
            $or: [
                { patientId: identifier.trim().toUpperCase() },
                { phoneNumber: identifier.trim() }
            ]
        });

        if (!patient) {
            return res.status(404).json({ message: "Patient not found." });
        }

        if (!patient.otp || patient.otp !== otp.trim()) {
            return res.status(400).json({ message: "Invalid OTP! Please check your SMS messages." });
        }

        if (patient.otpExpires && patient.otpExpires < new Date()) {
            return res.status(400).json({ message: "OTP has expired. Please request a new one." });
        }

        // Clear OTP once verified
        patient.otp = undefined;
        patient.otpExpires = undefined;
        await patient.save();

        const doctor = await Doctor.findOne({ doctorId: patient.assignedDoctorId });

        res.status(200).json({
            message: "OTP Verified! Logged in successfully.",
            patient: {
                patientId: patient.patientId,
                name: patient.name,
                age: patient.age,
                gender: patient.gender,
                phoneNumber: patient.phoneNumber,
                photoUrl: patient.photoUrl,
                currentStatus: patient.currentStatus,
                assignedDoctor: doctor ? {
                    doctorId: doctor.doctorId,
                    name: doctor.name,
                    department: doctor.department,
                    photoUrl: doctor.photoUrl,
                    currentQueueCount: doctor.currentQueueCount
                } : null
            }
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// 5. API: Update Patient Profile (Photo, Phone Number, Password, Name, etc.)
exports.updateProfile = async (req, res) => {
    try {
        const { patientId } = req.params;
        const { name, phoneNumber, password, photoUrl, age, gender } = req.body;

        const patient = await Patient.findOne({ patientId });
        if (!patient) {
            return res.status(404).json({ message: "Patient not found!" });
        }

        if (name) patient.name = name;
        if (phoneNumber) patient.phoneNumber = phoneNumber;
        if (password) patient.password = password;
        if (photoUrl !== undefined) patient.photoUrl = photoUrl;
        if (age) patient.age = age;
        if (gender) patient.gender = gender;

        await patient.save();

        res.status(200).json({
            message: "Profile and account details updated successfully!",
            patient,
            whatsAppNotification: {
                recipient: patient.phoneNumber,
                message: `🔐 *Chikitsya Setu Profile Update*\nHello *${patient.name}*,\nYour account details (Mobile / Password / Profile Photo) have been updated successfully.\n\n📱 *Updated Mobile:* +91 ${patient.phoneNumber}\n🔑 *Passcode:* ${patient.password}`
            }
        });
    } catch (error) {
        res.status(500).json({ message: "Error updating profile", error: error.message });
    }
};

